sudo: required
language: generic 
services:
  - docker
before_install:
  - docker build -t neethumohan1212/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true neethumohan1212/react-test npm run test
after_success:
  - docker build -t neethumohan1212/multi-client ./client
  - docker build -t neethumohan1212/multi-nginx ./nginx
  - docker build -t neethumohan1212/multi-server ./server
  - docker build -t neethumohan1212/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push neethumohan1212/multi-client
  - docker push neethumohan1212/multi-nginx
  - docker push neethumohan1212/multi-server
  - docker push neethumohan1212/multi-worker